Several improvements to detect agents and manage them

diff --git a/ssha b/ssha
--- a/ssha
+++ b/ssha
@@ -7,11 +7,6 @@
 # the following will not work since we are sourcing this file
 # program=$(basename $0)
 sshinfo=$HOME/.ssh-agent-info
-args_ssha=""
-verbose_ssha=""
-actions_ssha="check connect start stop restart"
-action_ssha="check"
-force_ssha=""
 
 vecho_ssha() {
   [ -z "$verbose_ssha" ]  || echo >&2 "$@"
@@ -62,6 +57,10 @@ do_ssha_check() {
       return 2
     else
       vecho_ssha "no SSH agent: $a"
+      unset SSH_AUTH_SOCK
+      unset SSH_AGENT_PID
+      unset SSHA
+      rm -f $sshinfo
       return 1
     fi
   fi
@@ -79,7 +78,7 @@ do_ssha_connect() {
     do_ssha_check
     rv=$?
   else
-    err "file not found: $sshinfo"     
+    vecho_ssha "file not found: $sshinfo"     
     rv=1
   fi
   if [ $rv -eq 1 ]; then
@@ -90,6 +89,23 @@ do_ssha_connect() {
       # echo checking this agent... $agent
       export SSH_AUTH_SOCK="$agent"
       export SSH_AGENT_PID=$(echo $agent | cut -d. -f2)
+      if [ -e "/proc/$SSH_AGENT_PID/comm" ]; then
+        comm="$(cat /proc/$SSH_AGENT_PID/comm)"
+      else
+        comm=""
+      fi
+      if [ "$comm" != "ssh-agent" ]; then
+        # try one pid higher
+        export SSH_AGENT_PID=$(($SSH_AGENT_PID + 1))
+        if [ -e "/proc/$SSH_AGENT_PID/comm" ]; then
+          comm="$(cat /proc/$SSH_AGENT_PID/comm)"
+        else
+          comm=""
+        fi
+        if [ "$comm" != "ssh-agent" ]; then
+	  unset SSH_AGENT_PID
+        fi
+      fi
       do_ssha_check
       rv=$?
       if [ $rv -ne 1 ]; then
@@ -105,7 +121,7 @@ do_ssha_connect() {
 
 do_ssha_start_agent() {
     vecho_ssha "Starting SSH agent"
-    eval $(ssh-agent)
+    eval $(ssh-agent) > /dev/null 2>&1
     export SSH_AUTH_SOCK
     export SSH_AGENT_PID
     export SSHA="$(date)"
@@ -114,22 +130,20 @@ do_ssha_start_agent() {
 }
 
 do_ssha_start() {
-    local check oldverbose=$verbose_ssha
+    local check
     vecho_ssha "--- ssha start ---"
     if [ -n "$force_ssha" ]; then
         do_ssha_start_agent
     else
-        verbose_ssha=""
         do_ssha_check
         check=$?
         if [ $check -eq 0 ]; then
-            verbose_ssha=$oldverbose
+            #verbose_ssha=$oldverbose
             vecho_ssha "SSH agent already running with key(s)"
         else
             if [ $check -eq 1 ]; then # no ssh agent
                 do_ssha_connect
                 check=$?
-                verbose_ssha=$oldverbose
                 if [ $check -eq 0 ]; then
                     vecho_ssha "Connected to a running SSH agent with key(s)"
                     return 0
@@ -150,16 +164,21 @@ do_ssha_start() {
 
 do_ssha_stop() {
   vecho_ssha "--- ssha stop ---"
-  local pid oldverbose=$verbose_ssha
+  local check pid # oldverbose=$verbose_ssha
   #verbose_ssha=""
-  if do_ssha_check; then
-    verbose_ssha=$oldverbose
+  do_ssha_check
+  check=$?
+  if [ $check -eq 1 ]; then
+    #verbose_ssha=$oldverbose
+    vecho_ssha "cannot stop SSH agent: not running"
+  else
+    #verbose_ssha=$oldverbose
     if [ -z "$SSH_AGENT_PID" ]; then
       vecho_ssha "Not stopping SSH agent: SSH_AGENT_PID is not set"
     else
       vecho_ssha "Stopping SSH agent"
       pid=$SSH_AGENT_PID
-      if [ $pid -gt 0 ]; then
+      if kill -0 $pid > /dev/null 2>&1 ; then
         unset SSH_AUTH_SOCK
         unset SSH_AGENT_PID
         unset SSHA
@@ -170,9 +189,6 @@ do_ssha_stop() {
         err "could not find PID for the ssh-agent"
       fi
     fi
-  else
-    verbose_ssha=$oldverbose
-    vecho_ssha "cannot stop SSH agent: not running"
   fi
   return 0
 }
@@ -180,6 +196,21 @@ do_ssha_stop() {
 do_ssha_restart() {
   do_ssha_stop
   do_ssha_start
+}
+
+do_ssha_passwordless() {
+  if do_ssha_connect; then
+    vecho_ssha "connected to the ssh-agent"
+  else
+    vecho_ssha "not connected to the ssh-agent, starting one now..."
+    do_ssha_start
+  fi
+  if ! do_ssha_check; then
+    vecho_ssha "adding key to ssh-agent..."
+    if ! ssh-add > /dev/null 2>&1 ; then
+      err "ssh key could not be added to ssh-agent (is it passwordless?)."
+    fi
+  fi
 }
 
 validaction() {
@@ -193,8 +224,13 @@ validaction() {
 }
 
 if [ -z "$ssha_functions" ]; then
+    actions_ssha="check connect start stop restart passwordless"
+    action_ssha="check"
+    args_ssha=""
+    verbose_ssha=""
+    force_ssha=""
     while [ "$#" -gt 0 ]; do
-        echo "arg=$1="
+        #echo "arg=$1="
         case "$1" in
             (-v|--verbose)
                 verbose_ssha="--verbose"
